### DISCUSSION TITLE
"Illegal Instruction" when trying to run virtual_webcam.py

### DISCUSSION THREAD

**Discussion by anomalyLuna** [allo-/virtual_webcam_background#73] [Q&A]
Hi all,
When I try to run virtual_webcam.py I keep getting the error "Illegal Instruction". That's literally all it says. I checked my virtual device and video device settings in config.yaml and switched them around a little and keep getting the same error no matter what settings I have. My config.yaml looks like this:

```
segmentation_threshold: 0.75
blur: 3
erode: 10
dilate: 10
virtual_video_device: "/dev/video2"
real_video_device: "/dev/video1"
average_masks: 3
mjpeg: False
- layers:
  - input: [["blur", 10]]
  - foreground: []
```

Anyone experienced something similar or have any ideas?
